cmake_minimum_required(VERSION 3.16)
project(dummy_collision_diagnostic)
find_package(ament_cmake REQUIRED)
find_package(rclcpp REQUIRED)
find_package(moveit_core REQUIRED)
find_package(moveit_msgs REQUIRED)
find_package(urdf REQUIRED)
find_package(srdfdom REQUIRED)
add_executable(collision_distance collision_distance.cpp)
target_compile_features(collision_distance PUBLIC cxx_std_17)
ament_target_dependencies(collision_distance rclcpp moveit_core moveit_msgs urdf srdfdom)
